name: data_check_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  # Core data and testing libraries with more modern versions
  - pandas~=2.1.3
  - numpy>=1.22
  - scipy>=1.9
  - pytest>=7.0

  - pip:
    - mlflow~=2.8.1
    - wandb~=0.16.0